### ISSUE TITLE
ebcl-ui ends with authentication error for artifactory

### ISSUE THREAD

**Issue by puhs273613** [Elektrobit/nautilos-repo-setup#3]
User ID: puhs273613
As a part of Tata MVP Project requirement, have to build Eblinux5 image using ebcl-ui command but receiving below error logs:-

While launching ebcl-UI (without VPN), when I select the EBCL Distribution testing/local, 
sometimes I’m getting Username/Password Authentication Failed. & sometimes ERROR 403: (no description).

puneeth@puneeth-VirtualBox:~/tata$ ./ebcl-ui 

--2023-04-06 12:12:39--  https://artifactory.elektrobit.com/eb_corbos_linux_nautilos2.0-debian-remote/release/xUbuntu_22.04_debbuild/all/

Resolving artifactory.elektrobit.com (artifactory.elektrobit.com)... 10.243.128.113

Connecting to artifactory.elektrobit.com (artifactory.elektrobit.com)|10.243.128.113|:443... connected.

HTTP request sent, awaiting response... 401 

Authentication selected: Basic realm="Artifactory Realm"

Reusing existing connection to artifactory.elektrobit.com:443.

HTTP request sent, awaiting response... 403 

2023-04-06 12:12:40 ERROR 403: (no description).

@schaefi Could you please help me for the above Issue.

**Comment by schaefi** [comment]
Hi, thanks for reporting.

So the other issues #4 and #5 are related to the same problem in my opinion. Thus let's focus on solving it once which will impact all other related problems you have. Therefore I'm closing #4 and #5 in favor of this one

**Comment by schaefi** [comment]
Ok, so to access artifactory two conditions must be met

- [ ] Access through Artifactory via EB VPN is known to be broken, connections are slow and breaks down occasionally. I have talked about this to the IT team and they told me they are reworking the entire openfortivpn based solution which is why they are not touching it for the moment. Ok. For us this means don't connect through VPN which actually was the whole idea anyways because customers have no VPN access ;) I'm just saying that because I know some colleagues continues to connect to artifactory via VPN and wonder how it behaves
- [ ] Your artifactory account must be eligible to access the two projects
       * https://artifactory.elektrobit.com/artifactory/eb_corbos_linux_nautilos2.0-releases-generic/
       * https://artifactory.elektrobit.com/artifactory/eb_corbos_linux_nautilos2.0-debian-remote/

**Comment by schaefi** [comment]
I tick off the first point because you told me you are not connecting through VPN

**Comment by schaefi** [comment]
I think you are suffering from the second check mark. In order to solve this you need to do the following

1. Open a ticket against the EB IT team, asking for permissions to access the two mentioned projects
2. Add me or Bogdan Maryniuk to the ticket such that we can see it and can approve your access request
3. EB IT has the admin rights to add you, we don't have these permissions
4. Give the system some time to resync (IT Team will tell you)

Once this is done you should not have any issues connecting.

Keep us posted. Thanks

**Comment by anjo273727** [comment]
Hi @schaefi , We have already the access for https://artifactory.elektrobit.com/artifactory/eb_corbos_linux_nautilos2.0-debian-remote/.
For the repo "https://artifactory.elektrobit.com/artifactory/eb_corbos_linux_nautilos2.0-debian-remote/", already raised and request to  @Wegler, Astrid.
We will follow up again once the requests are granted.
Thanks @schaefi .

**Comment by puhs273613** [comment]
We were able to create and launch qemu image after getting all the artifactory access.

**Comment by puhs273613** [comment]
Thank you @schaefi  for the support,
Closing the ticket as the issue is resolved.
